# Setup
title:        ∀
tagline:      The blog of Ivan λ Morozov
baseurl:      ""
paginate:     2

# About/contact
author:
  name:       Ivan Morozov
  url:        http://allquantor.github.io/about

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
