# Setup
title:        Allquantor's Blog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Ivan Morozov
  url:        http://allquantor.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
